common: &common
  adapter: postgresql
  encoding: utf8
  database: active_admin_db
  username: user12
  password: pakistan
  host: "localhost"
  port: <%= ENV['DB_PORT'] %>

production:
  <<: *common

staging:
  <<: *common

test: &test
  <<: *common
  database: <%= ENV["active_admin_test"] %>

development:
  <<: *common

